### ISSUE TITLE
Incorrect Decrement in delete_employee 

### ISSUE THREAD

**Issue by Fairgrieve** [SweatyCarrot/DatabaseProject#1]
line 187: empnum-1;
should be empnum--

:)

**Comment by SweatyCarrot** [comment]
~~Textedyou back, but line 187 and the comment after it aren't even doing anything/accurate anymore. I went through a few different versions of that function and forgot to get rid of that lol.~~
~~Thanks. I'll fix it in my next commit.~~

EDIT: Nvm, I am dumb. delete_employee() must have been broken this whole time. Thanks, it will be fixed.

**Comment by SweatyCarrot** [comment]
Fixed by commit 644fe60
